version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test

      # install aws cli
      - run: sudo apt-get update && sudo apt-get install -y awscli
      - run: aws --version
      - run: aws s3 ls

      - run: gradle shadowJar

      # deploy to aws lambda
#      - run: aws lambda create-function --region ap-southeast-2 --function-name incognito-record-get-posts-lambda --runtime java8 --handler nz.co.incognito.record.MainHandler::handleRequest --memory-size 128 --zip-file "fileb://build/libs/incognito-record-1.0-SNAPSHOT-all.jar" --role arn:aws:iam::445825595815:role/lambda_basic_execution

      - run: aws lambda update-function-code --region ap-southeast-2 --function-name incognito-record-get-posts-lambda --zip-file "fileb://build/libs/incognito-record-1.1-SNAPSHOT-all.jar" || aws lambda create-function --region ap-southeast-2 --function-name incognito-record-get-posts-lambda --runtime java8 --handler nz.co.incognito.record.MainHandler::handleRequest --memory-size 512 --zip-file "fileb://build/libs/incognito-record-1.0-SNAPSHOT-all.jar" --role arn:aws:iam::445825595815:role/lambda_basic_execution